name: stratis_flutter
description: A plugin that communicates with the Stratis daemon over D-Bus.
version: 0.0.1
author: Carmine Zaccagnino <carmine@carminezacc.com>
homepage: https://github.com/carzacc/flutter_stratis_plugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.3.0 <3.0.0"